### ISSUE TITLE
Requirements checklist

### ISSUE THREAD

**Issue by Varia321** [WomenPlusPlus/deploy-impact-22-wikimini-c#90]
- [x] Code must be provided in a public GitHub repository
- [x] All supporting work and datasets must be referenced and properly attributed (this includes 3rd party libraries, code taken from forums etc.)
- [x] a LICENSE file that contains the text for the GPL v3 License (see [Github's recommendations](https://docs.github.com/en/rest/reference/licenses) for more information on how to apply this)
- [x] Instructions on running must be provided (ideally in the README or linked to)
- [x] The repository should be in a complete state in that it is not filled with TODOs or empty boilerplate code. Slim it down!
- [x] Nominate a contact person who can coordinate any further development with the product owner on behalf of your team
- [x] For Wikimini project teams: URL to access the wiki if it is not stored in the repository
